 # Dark Sky
- platform: darksky
  api_key: !secret darksky_key
  forecast:
    - 0
  hourly_forecast:
    - 0
    - 1
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - temperature_high
    - temperature_low
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - visibility
    - moon_phase
    - alerts

# Met Office
#- platform: metoffice
#  api_key: 02a7ca4a-613c-4446-a64d-622dd12865dc
#  monitored_conditions:
#    - weather
#    - temperature
#    - feels_like_temperature
#    - wind_speed
#    - wind_direction
#    - wind_gust
#    - visibility
#    - visibility_distance
#    - uv
#    - precipitation
#    - humidity