- platform: systemmonitor
  resources:
    - type: disk_free
    - type: disk_use
      arg: /home
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use
    - type: memory_use_percent
    - type: process
    - type: processor_use
    - type: last_boot
    - type: ipv4_address
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0